-- BANCO DE DADOS SISTEMA JACKSONDB
-- CRIANDO O BANCO
CREATE DATABASE IF NOT EXISTS `flysysdb`;

-- HABILITANDO O BANCO PARA USO
USE jacksonDB;


-- CRIANDO TABELA AERONAVE
CREATE TABLE IF NOT EXISTS `AERONAVE`(
	`AERONAVE_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`MARCA` VARCHAR(255) NOT NULL,
    `MODELO` VARCHAR(255) NOT NULL,
	`COR` VARCHAR(255) NOT NULL,
	`TIPO` VARCHAR(255) NOT NULL,
	`PREFIXO` VARCHAR(6) NOT NULL,
    `CAPACIDADE` INT UNSIGNED NOT NULL
    `COMPANHIA_ID` INT UNSIGNED NOT NULL
	PRIMARY KEY (`AERONAVE_ID`),
	UNIQUE INDEX `AERONAVE_ID_UNIQUE` (`AERONAVE_ID`ASC ))
	ENGINE = InnoDB;
-- CONSULTANDO AERONAVE
SELECT * FROM aeronave;
INSERT INTO `AERONAVE` (`AERONAVE_ID`, `MARCA`, `MODELO`, `COR`, `TIPO`, `PREFIXO`, `CAPACIDADE`, `COMPANHIA_ID`) VALUES
(1, 'AIRBUS', 'A300', 'BRANCA', 'JATO', 'PR‑YRA', 'PR‑YRA', 5);
-- CRIANDO TABELA CLIENTE
CREATE TABLE IF NOT EXISTS `CLIENTE`(
	`CLIENTE_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`NAME_CLIENTE` VARCHAR(50) NOT NULL,
    `CPF_CLIENTE` VARCHAR(50) NOT NULL,
	PRIMARY KEY (`CLIENTE_ID`),
	UNIQUE INDEX `CLIENTE_ID_UNIQUE` (`CLIENTE_ID`ASC ))
	ENGINE = InnoDB;
-- CONSULTANDO CLIENTE
SELECT * FROM cliente;

-- CRIANDO TABELA PEDIDO
CREATE TABLE IF NOT EXISTS `PEDIDO`(
	`PEDIDO_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`CLIENTE_ID` SMALLINT(5),
    `PRODUTO_ID` SMALLINT(5),
    `QTDE_PRODUTO` DECIMAL(4,2) NOT NULL,
    `DATA_PEDIDO` DATETIME,
    `VALOR_PEDIDO` DECIMAL(4,2) NOT NULL,
	PRIMARY KEY (`PEDIDO_ID`),
	UNIQUE INDEX `PEDIDO_ID_UNIQUE` (`PEDIDO_ID`ASC ))
	ENGINE = InnoDB;
-- CONSULTANDO PEDIDO
SELECT * FROM pedido;

-- CRIANDO TABELA ITENS_PEDIDO
CREATE TABLE IF NOT EXISTS `ITENS_PEDIDO`(
	`ITENS_PEDIDO_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`PEDIDO_ID` SMALLINT(5),
    `PRODUTO_ID` SMALLINT(5),
    `DATA_PEDIDO` DATETIME,
	PRIMARY KEY (`ITENS_PEDIDO_ID`),
	UNIQUE INDEX `ITENS_PEDIDO_ID_UNIQUE` (`ITENS_PEDIDO_ID`ASC ))
	ENGINE = InnoDB;
-- CONSULTANDO PEDIDO
SELECT * FROM itens_pedido;