-- BANCO DE DADOS SISTEMA Flaysys
-- CRIANDO O BANCO
CREATE DATABASE IF NOT EXISTS `flysysdb`;

-- HABILITANDO O BANCO PARA USO
USE flysysdb;

-- CRIANDO TABELA AERONAVE --------------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `AERONAVE`(
	`ID_AERONAVE` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`MARCA` VARCHAR(50) NOT NULL,
    `MODELO` VARCHAR(50) NOT NULL,
	`COR` VARCHAR(30) NOT NULL,
	`TIPO` VARCHAR(50) NOT NULL,
	`PREFIXO` VARCHAR(10) NOT NULL,
    `CAPACIDADE` INT UNSIGNED NOT NULL,
	`VELOCIDADE` VARCHAR(20) NOT NULL,
    `ID_COMPANHIA` INT UNSIGNED NOT NULL,
	`ID_HANGAR` INT UNSIGNED NOT NULL,
	PRIMARY KEY (`ID_AERONAVE`),
	UNIQUE INDEX `ID_AERONAVE_UNIQUE` (`ID_AERONAVE`ASC))
	ENGINE = InnoDB;
-- CONSULTANDO AERONAVE
SELECT * FROM aeronave;
-- INSERINDO DADOS NA TABELA AERONAVE
INSERT INTO `AERONAVE` (`ID_AERONAVE`, `MARCA`, `MODELO`, `COR`, `TIPO`, `PREFIXO`, `CAPACIDADE`, `VELOCIDADE`, `ID_COMPANHIA`, `ID_HANGAR`)
	VALUES (1, 'AIRBUS', 'A300', 'BRANCA', 'JATO', 'PR‑YRA', '853', '500km/h', 5, 6);

-- CRIANDO TABELA HANGAR ----------------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `HANGAR`(
	`ID_HANGAR` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`NOME_HANGAR` VARCHAR(60) NOT NULL,
    `ID_AERONAVE` VARCHAR(20) NOT NULL,
	PRIMARY KEY (`ID_HANGAR`),
	UNIQUE INDEX `ID_HANGAR_UNIQUE` (`ID_HANGAR`ASC))
	ENGINE = InnoDB;
-- CONSULTANDO HANGAR
SELECT * FROM hangar;
-- INSERINDO DADOS NA TABELA HANGAR
INSERT INTO `HANGAR` (`ID_HANGAR`, `NOME_HANGAR`, `ID_AERONAVE`)
	VALUES (1, 'AB5532', 6);

-- CRIANDO TABELA PISTA -----------------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `PISTA`(
	`ID_PISTA` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`NUMERO_PISTA` SMALLINT(60),
	PRIMARY KEY (`ID_PISTA`),
	UNIQUE INDEX `ID_PISTA_UNIQUE` (`ID_PISTA`ASC))
	ENGINE = InnoDB;
-- CONSULTANDO PISTA
SELECT * FROM pista;
-- INSERINDO DADOS NA TABELA PISTA
INSERT INTO `PISTA` (`ID_PISTA`, `NUMERO_PISTA`)
	VALUES (1, 'AB5532', 6);

-- CRIANDO TABELA COMPANHIA -------------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `ID_COMPANHIA`(
	`ID_COMPANHIA` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`NOME_COMPANHIA` SMALLINT(60),
    `CNPJ` SMALLINT(18),
    `DATA_PEDIDO` DATETIME,
	PRIMARY KEY (`ID_COMPANHIA`),
	UNIQUE INDEX `ID_COMPANHIAUNIQUE` (`ID_COMPANHIA`ASC))
	ENGINE = InnoDB;
-- CONSULTANDO COMPANHIA
SELECT * FROM companhia;
-- INSERINDO DADOS NA TABELA PISTA 
INSERT INTO `COMPANHIA` (`ID_COMPANHIA`, `NOME_COMPANHIA`, `CNPJ`)
	VALUES (1, 'Emirates', '08.680.648/0001-68');

-- CRIANDO TABELA VOO --------------------------------------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `voo`(
	`ID_VOO` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`NUMERO` VARCHAR(50) NOT NULL,
    `DATA` DATE,
	`ORIGEM` VARCHAR(3) NOT NULL,
	`DESTINO` VARCHAR(3) NOT NULL,
	`PILOTO` VARCHAR(50) NOT NULL,
	`COPILOTO` VARCHAR(50) NOT NULL,
	`OBSERVACAO` VARCHAR(255) NOT NULL,
    `ID_PISTA` INT UNSIGNED NOT NULL,
	`ID_AERONAVE` INT UNSIGNED NOT NULL,
	PRIMARY KEY (`ID_VOO`),
	UNIQUE INDEX `ID_VOO_UNIQUE` (`ID_VOO`ASC))
	ENGINE = InnoDB;
-- CONSULTANDO VOO
SELECT * FROM voo;
-- INSERINDO DADOS NA TABELA VOO
INSERT INTO `VOO` (`ID_VOO`, `NUMERO`, `DATA`, `ORIGEM`, `DESTINO`, `PILOTO`, `COPILOTO`, `OBSERVACAO`, `ID_PISTA`, `ID_AERONAVE`)
VALUES (1, '556633', '2022-11-24', 'JOIN', 'CWB', 'JAIR BOLSONARO', 'LUIZ INÁCIO', 'CAMPO RESERVADO PARA OBSERVAÇÕES', 2, 1);